### ISSUE TITLE
Error occurs, please double check you enter the correct email address.

### ISSUE THREAD

**Issue by zhaoyuanxing** [cvdfoundation/open-images-dataset#2]
i fill the Access Requst Form but get the message:

Error occurs, please double check you enter the correct email address.

my form is as follow:

name: zyx
organization: hisign
gmail: zhao.yuanxinghh@gmail.com
usage: detection

**Comment by rkrasin** [comment]
@zhaoyuanxing I have entered the exact information you have provided above and it gave me:

```
You have successfully signed up for downloading Open Images Dataset
```

Whatever the issue was, it was transient. Note: I am not a part of cvdfountation team, and don't have the access to logs to see what actually happened.

Please, check out your inbox. There shall be a welcome message arrived in a few minutes.

**Comment by zhaoyuanxing** [comment]
thank you very much
